### ISSUE TITLE
Support XacmlJsonUtils to load schema files from alternative location

### ISSUE THREAD

**Issue by securedimensions** [authzforce/xacml-json-model#5]
# Schema files are not loaded from alternative location

The loading of a custom `request` schema in JSON cannot be achieved, because the class `XacmlJsonUtils` seem to only load the schema files from classpath.

## Code snippets
In https://github.com/authzforce/xacml-json-model/blob/develop/src/main/java/org/ow2/authzforce/xacml/json/model/XacmlJsonUtils.java lines 67, 68, 69 the schema file names are hardcoded:

```java
static
    {
        REQUEST_SCHEMA = loadSchema("Request.schema.json");
        RESPONSE_SCHEMA = loadSchema("Response.schema.json");
        POLICY_SCHEMA = loadSchema("Policy.schema.json");
    }
```

In https://github.com/authzforce/xacml-json-model/blob/develop/src/main/java/org/ow2/authzforce/xacml/json/model/XacmlJsonUtils.java line 40, the schema files are loaded from classpath (JAR):

```java
private static Schema loadSchema(String schemaFilenameRelativeToThisClass)
    {
        try (InputStream inputStream = XacmlJsonUtils.class.getResourceAsStream(schemaFilenameRelativeToThisClass))
        {
            final JSONObject rawSchema = new JSONObject(new JSONTokener(inputStream));
            return SchemaLoader.builder().schemaJson(rawSchema).schemaClient(CLASSPATH_AWARE_SCHEMA_CLIENT).resolutionScope("classpath://org/ow2/authzforce/xacml/json/model/").build().load().build();
        } catch (final IOException e)
        {
            throw new RuntimeException(e);
        }
    }
```
This behavior cannot "simply" be overwritten, as the class `XacmlJsonUtils` is `final`:

```java
public final class XacmlJsonUtils
```

## Enhancement request
Please support loading of request schema as configured with `jndi_xacmlJsonSchemaRelativePath`

**Comment by cdanger** [comment]
If you mention jndi_xacmlJsonSchemaRelativePath, this applies to AuthzForce Server only. This XacmlJsonUtils is only for loading the default XACML/JSON schema. It is not used for loading a custom schema (the method is private anyway), another class is used for loading a custom schema by AuthzForce Server (JsonRiCxfJaxrsProvider), as you can see here:
https://github.com/authzforce/server/blob/master/webapp/src/main/webapp/WEB-INF/beans.xml#L146
